delivery/urls.py
from django.contrib import admin
from django.urls import path

from . import views
app_name = 'delivery'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    # PRODUCTS
    path('product_list/', views.ProductListView.as_view(), name='product_list'),
    path('product/create/', views.ProductCreateView.as_view(), name='product_create'),
    path('product/detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/update/<int:pk>/', views.ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product_delete'),

    # PERSONNEL
    path('personnel_list/', views.PersonnelListView.as_view(), name='personnel_list'),
    path('personnel/create/', views.PersonnelCreateView.as_view(), name='personnel_create'),
    path('personnel/detail/<int:pk>/', views.PersonnelDetailView.as_view(), name='personnel_detail'),
    path('personnel/update/<int:pk>/', views.PersonnelUpdateView.as_view(), name='personnel_update'),
    path('personnel/delete/<int:pk>/', views.PersonnelDeleteView.as_view(), name='personnel_delete'),

    # SUPPLIER
    path('supplier/list/', views.SupplierListView.as_view(), name='supplier_list'),
    path('supplier/create/', views.SupplierCreateView.as_view(), name='supplier_create'),
    path('supplier/update/<int:pk>/', views.SupplierUpdateView.as_view(), name='supplier_update'),
    path('supplier/delete/<int:pk>/', views.SupplierDeleteView.as_view(), name='supplier_delete'),

    # ORDER_PRODUCT
    path('order_list/', views.OrderListView.as_view(), name='order_list'),
    path('order/create/', views.OrderCreateView.as_view(), name='order_create'),

    # PRODUCT_SUPPLY
    path('product_supply/list/', views.ProductSupplyListView.as_view(), name='product_supply'),
    path('product_supply/create/', views.ProductSupplyCreateView.as_view(), name='product_supply_create'),

    # PRODUCT_SALE
    path('product_sale/', views.ProductSaleListView.as_view(), name='product_sale'),
    path('product_sale/create/', views.ProductSaleCreateView.as_view(), name='product_sale_create'),

    # SALARY
    path('salary/list/', views.SalaryListView.as_view(), name='salary_list'),
    path('salary/create/', views.SalaryCreateView.as_view(), name='salary_create'),

    # CUSTOMER
    path('customer/list/', views.CustomerListView.as_view(), name='customers'),
    path('customer/detail/<int:pk>/', views.CustomerDetailView.as_view(), name='customer_detail'),
    path('customer/create/', views.CustomerCreateView.as_view(), name='customer_create'),
    path('customer/update/<int:pk>/', views.CustomerUpdateView.as_view(), name='customer_update'),
    path('customer/delete/<int:pk>/', views.CustomerDeleteView.as_view(), name='customer_delete'),

    # INCOMES
    path('incomes/', views.IncomeListView.as_view(), name='incomes'),
    path('income/create/', views.IncomeCreateView.as_view(), name='income_create'),

    # EXPENSES
    path('expenses/', views.ExpenseListView.as_view(), name='expenses'),
    path('expense/create/', views.ExpenseCreateView.as_view(), name='expense_create'),

    # ACCOUNTINGS
    path('accounting/', views.AccountingListView.as_view(), name='accounting'),
    path('accounting/create/', views.AccountingCreateView.as_view(), name='accounting_create'),

    path('login/', views.ProjectLoginView.as_view(), name='login_page'),
    path('register/', views.RegisterUserView.as_view(), name='register_page'),
    path('logout/', views.MyProjectLogout.as_view(), name='logout_page'),

]

pharmacy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('delivery.urls'))
]

delivery/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm

from .models import *


class AuthUserForm(AuthenticationForm, forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')


class RegisterUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

delivery/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth import authenticate, login


from .forms import *
from .models import *
from .views import *


def home_page(request):
    return render(request, 'delivery/home.html')

# PRODUCT CRUD VIEW

class ProductListView(ListView):

    model = Product
    template_name = 'delivery/products/product_list.html'
    context_object_name = 'object_list'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        object_list = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(object_list, self.paginate_by)
        try:
            object_list = paginator.page(page)
        except PageNotAnInteger:
            object_list = paginator.page(1)
        except EmptyPage:
            object_list = paginator.page(paginator.num_pages)
        context['object_list'] = object_list
        return context


class ProductCreateView(CreateView):
    model = Product
    template_name = 'delivery/products/product_create.html'
    fields = '__all__'
    success_url = reverse_lazy('delivery:product_list')


class ProductDetailView(DetailView):
    model = Product
    template_name = 'delivery/products/product_detail.html'


class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'delivery/products/product_update.html'
    context_object_name = 'product'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('delivery:product_detail', kwargs={'pk': self.object.pk})


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'delivery/products/product_delete.html'
    success_url = reverse_lazy('delivery:product_list')



# PERSONNEL CRUD VIEW

class PersonnelListView(ListView):

    model = Personnel
    template_name = 'delivery/personnel/personnel_list.html'
    context_object_name = 'personnels'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(PersonnelListView, self).get_context_data(**kwargs)
        personnels = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(personnels, self.paginate_by)
        try:
            personnels = paginator.page(page)
        except PageNotAnInteger:
            personnels = paginator.page(1)
        except EmptyPage:
            personnels = paginator.page(paginator.num_pages)
        context['personnels'] = personnels
        return context

class PersonnelCreateView(CreateView):
    model = Personnel
    template_name = 'delivery/personnel/personnel_create.html'
    fields = '__all__'
    success_url = reverse_lazy('delivery:personnel_list')


class PersonnelDetailView(DetailView):
    model = Personnel
    template_name = 'delivery/personnel/personnel_detail.html'


class PersonnelUpdateView(UpdateView):
    model = Personnel
    template_name = 'delivery/personnel/personnel_update.html'
    context_object_name = 'personnel'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('delivery:personnel_detail', kwargs={'pk': self.object.id})


class PersonnelDeleteView(DeleteView):
    model = Personnel
    template_name = 'delivery/personnel/personnel_delete.html'
    success_url = reverse_lazy('delivery:personnel_list')



# SUPPLIER CRUD VIEW

class SupplierListView(ListView):

    model = Supplier
    template_name = 'delivery/suppliers/supplier_list.html'
    context_object_name = 'suppliers'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(SupplierListView, self).get_context_data(**kwargs)
        suppliers = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(suppliers, self.paginate_by)
        try:
            suppliers = paginator.page(page)
        except PageNotAnInteger:
            suppliers = paginator.page(1)
        except EmptyPage:
            suppliers = paginator.page(paginator.num_pages)
        context['suppliers'] = suppliers
        return context


class SupplierCreateView(CreateView):
    model = Supplier
    template_name = 'delivery/suppliers/supplier_create.html'
    fields = '__all__'
    success_url = reverse_lazy('delivery:supplier_list')


class SupplierUpdateView(UpdateView):
    model = Supplier
    template_name = 'delivery/suppliers/supplier_update.html'
    context_object_name = 'supplier'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('delivery:supplier_list')


class SupplierDeleteView(DeleteView):
    model = Supplier
    template_name = 'delivery/suppliers/supplier_delete.html'
    success_url = reverse_lazy('delivery:supplier_list')



# ORDER_PRODUCT CRUD VIEW

class OrderListView(ListView):
    model = Order_product
    template_name = 'delivery/order_product/order_list.html'
    context_object_name = 'orders'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(OrderListView, self).get_context_data(**kwargs)
        orders = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(orders, self.paginate_by)
        try:
            orders = paginator.page(page)
        except PageNotAnInteger:
            orders = paginator.page(1)
        except EmptyPage:
            orders = paginator.page(paginator.num_pages)
        context['orders'] = orders
        return context


class OrderCreateView(CreateView):
    model = Order_product
    template_name = 'delivery/order_product/order_create.html'
    fields = '__all__'
    success_url = reverse_lazy('delivery:order_list')



# PRODUCT_SUPPLY CRUD VIEW

class ProductSupplyListView(ListView):
    model = Product_supply
    template_name = 'delivery/product_supply/product_supply.html'
    context_object_name = 'supplies'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(ProductSupplyListView, self).get_context_data(**kwargs)
        supplies = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(supplies, self.paginate_by)
        try:
            supplies = paginator.page(page)
        except PageNotAnInteger:
            supplies = paginator.page(1)
        except EmptyPage:
            supplies = paginator.page(paginator.num_pages)
        context['supplies'] = supplies
        return context



class ProductSupplyCreateView(CreateView):
    model = Product_supply
    template_name = 'delivery/product_supply/product_supply_create.html'
    fields = '__all__'
    success_url = reverse_lazy('delivery:product_supply')



# PRODUCT_SALE CRUD VIEW

class ProductSaleListView(ListView):
    model = Product_sale
    template_name = 'delivery/product_sale/product_sale.html'
    context_object_name = 'sales'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(ProductSaleListView, self).get_context_data(**kwargs)
        sales = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(sales, self.paginate_by)
        try:
            sales = paginator.page(page)
        except PageNotAnInteger:
            sales = paginator.page(1)
        except EmptyPage:
            sales = paginator.page(paginator.num_pages)
        context['sales'] = sales
        return context


class ProductSaleCreateView(CreateView):
    model = Product_sale
    template_name = 'delivery/product_sale/product_sale_create.html'
    fields = '__all__'
    success_url = reverse_lazy('delivery:product_sale')

# SALARY CRUD VIEW

class SalaryListView(ListView):
    model = Salary
    template_name = 'delivery/salary/salary_list.html'
    context_object_name = 'salaries'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(SalaryListView, self).get_context_data(**kwargs)
        salaries = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(salaries, self.paginate_by)
        try:
            salaries = paginator.page(page)
        except PageNotAnInteger:
            salaries = paginator.page(1)
        except EmptyPage:
            salaries = paginator.page(paginator.num_pages)
        context['salaries'] = salaries
        return context


class SalaryCreateView(CreateView):
    model = Salary
    template_name = 'delivery/salary/salary_create.html'
    fields = '__all__'
    success_url = reverse_lazy('delivery:salary_list')



# CUSTOMER CRUD VIEW

class CustomerListView(ListView):
    model = Customer
    template_name = 'delivery/customers/customers.html'
    context_object_name = 'customers'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(CustomerListView, self).get_context_data(**kwargs)
        customers = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(customers, self.paginate_by)
        try:
            customers = paginator.page(page)
        except PageNotAnInteger:
            customers = paginator.page(1)
        except EmptyPage:
            customers = paginator.page(paginator.num_pages)
        context['customers'] = customers
        return context


class CustomerDetailView(DetailView):
    model = Customer
    template_name = 'delivery/customers/customer_detail.html'


class CustomerCreateView(CreateView):
    model = Customer
    template_name = 'delivery/customers/customer_create.html'
    fields = '__all__'
    success_url = reverse_lazy('delivery:customers')


class CustomerUpdateView(UpdateView):
    model = Customer

templates/delivery/customers/customer_create.html
{% extends "delivery/create.html" %}

{% block item %}
        customer
{% endblock item %}

templates/delivery/customers/customer_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">Delete Customer #{{object.id}}</h5>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="alert alert-warning" role="alert">
                    Are you sure you want to delete <strong>{{ object }}</strong> ?
                </div>
                <button type="submit" class="btn-danger">Delete</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/delivery/customers/customer_detail.html
{% extends "base.html" %}
{% block content %}

    <div class="card">
        <div class="card-header">
            <h5 class="card-title">Personnel Details #{{ customer.id }}</h5>

        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-3">ID</dt>
                <dd class="col-sm-9">{{ customer.id }}</dd>
                <dt class="col-sm-3">Фио</dt>
                <dd class="col-sm-9">
                    {{ customer.first_name }}
                    {{ customer.last_name }}
                    {{ customer.patronymic }}
                </dd>
                <dt class="col-sm-3">Адрес</dt>
                <dd class="col-sm-9">{{ customer.address }}</dd>
                <dt class="col-sm-3">Номер телефона</dt>
                <dd class="col-sm-9">{{ customer.phone_num }}</dd>
                <dt class="col-sm-3">Серия паспорта</dt>
                <dd class="col-sm-9">{{ customer.serial_pas_c }}</dd>
                <dt class="col-sm-3">Номер паспорта</dt>
                <dd class="col-sm-9">{{ customer.number_pas_c }}</dd>

            </dl>
            {% if user.is_superuser %}
                <button type="submit "class="btn-success card-title">
                    <a href="{% url 'delivery:customer_update' pk=object.pk %}">
                        Edit
                    </a>
                </button>
                <button type="submit" class="btn-danger card-title">
                    <a href="{% url 'delivery:customer_delete' pk=object.pk %}">
                        Delete
                    </a>
                </button>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/delivery/customers/customer_update.html
{% extends "base.html" %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">Customer Update #{{ customer.id }}</h5>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn-success">Update</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/delivery/customers/customers.html
{% extends 'base.html' %}

{% block header %}
    < На главную
{% endblock header %}

{% block content %}
    <br>
    <table class="table">
        <tr>
            <thead class="thead-light">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">ФИО</th>
                    <th scope="col">Номер</th>
                </tr>
            </thead>
            <tbody>
                {% for customer in customers %}
                    <tr>
                        <td>{{ customer.id }}</td>
                        <td>
                            <a href="{% url 'delivery:customer_detail' pk=customer.pk %}">
                                {{ customer.first_name }}
                                {{ customer.last_name }}
                                {{ customer.patronymic}}
                            </a>
                        </td>
                        <td>{{ customer.phone_num }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </tr>
    </table>
    <nav aria-label="Page navigation example">
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.previous_page_number}}">
                            &laquo;
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">&laquo;</a>
                    </li>
                {% endif %}

                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="page-item"><a class="page-link active">{{ i }}</a></li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="?page={{page_obj.next_page_number}}" class="page-link">
                            &raquo;
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&raquo;</a>
                    </li>
                {% endif %}
            </ul>
        {% endif %}
    </nav>
    {% if user.is_superuser %}
        <a href="{% url 'delivery:customer_create' %}"><button class="btn-success">+Добавить</button></a>
    {% endif %}
{% endblock %}